# Spam Classifier
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
Spam refers to unwanted email, often in the form of advertisements. In the literature, an email that is **not** spam is called *ham*. Most email providers offer automatic spam filtering, where spam emails will be moved to a separate inbox based on their contents. Of course this requires being able to scan an email and determine whether it is spam or ham, a classification problem. This is the subject of this assignment.

This assignment has two parts. Each part is worth 50% of the overall grade for this assignment.

For part one you will write a supervised learning based classifier to determine whether a given email is spam or ham. You must write and submit the code in this notebook. The training data is provided for you. You may use any classification method. Marks will be awarded primarily based on the accuracy of your classifier on unseen test data, but there are also marks for estimating how accurate you think your classifier will be.

In part two you will produce a short video explaining your implementation, any decisions or extensions you made, and what parameter values you used. This part is explained in more detail on the assignment page. The video file must be submitted with your assignment.

### Choice of Algorithm
While the classification method is a completely free choice, the assignment folder includes [a separate notebook file](data/naivebayes.ipynb) which can help you implement a Naïve Bayes solution. If you do use this notebook, you are still responsible for porting your code into *this* notebook for submission. A good implementation should give a high  enough accuracy to get a good grade on this section (50-70%).

You could also consider a k-nearest neighbour algorithm, but this may be less accurate. Logistic regression is another option that you may wish to consider.

If you are looking to go beyond the scope of the unit, you might be interested in building something more advanced, like an artificial neural network. This is possible just using `numpy`, but will require significant self-directed learning. *Extensions like this are left unguided and are not factored into the unit workload estimates.*

**Note:** you may use helper functions in libraries like `numpy` or `scipy`, but you **must not** import code which builds entire models for you. This includes but is not limited to use of libraries like `scikit-learn`, `tensorflow`, or `pytorch` – there will be plenty of opportunities for these libraries in later units. The point of this assignment is to understand code the actual algorithm yourself. ***If you are in any doubt about any particular library or function please ask a tutor.*** Submissions which ignore this will receive penalties or even zero marks.

If you choose to implement more than one algorithm, please feel free to include your code and talk about it in part two (your video presentation), but only the code in this notebook will be used in the automated testing.

## Training Data
The training data is described below and has 1000 rows. There is also a 500 row set of test data. These are functionally identical to the training data, they are just in a separate csv file to encourage you to split out your training and test data. You should consider how to best make use of all available data without overfitting, and to help produce an unbiased estimate for your classifier's accuracy.

The cell below loads the training data into a variable called `training_spam`.

In [1]:
import numpy as np
from IPython.display import HTML,Javascript, display

training_spam = np.loadtxt(open("data/training_spam.csv"), delimiter=",").astype(int)
print("Shape of the spam training data set:", training_spam.shape)
print(training_spam)

Shape of the spam training data set: (1000, 55)
[[1 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [1 1 1 ... 1 1 0]
 [1 0 0 ... 1 1 1]]


Your training set consists of 1000 rows and 55 columns. Each row corresponds to one email message. The first column is the _response_ variable and describes whether a message is spam `1` or ham `0`. The remaining 54 columns are _features_ that you will use to build a classifier. These features correspond to 54 different keywords (such as "money", "free", and "receive") and special characters (such as ":", "!", and "$"). A feature has the value `1` if the keyword appears in the message and `0` otherwise.

As mentioned there is also a 500 row set of *test data*. It contains the same 55 columns.

In [2]:
testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(int)
print("Shape of the spam testing data set:", testing_spam.shape)
print(testing_spam)

Shape of the spam testing data set: (500, 55)
[[1 0 0 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]


## Part One
Write all of the code for your classifier below this cell. There is some very rough skeleton code in the cell directly below. You may insert more cells below this if you wish, but you must not duplicate any cells as this can break the grading script.

### Submission Requirements
Your code must provide a variable with the name `classifier`. This object must have a method called `predict` which takes input data and returns class predictions. The input will be a single $n \times 54$ numpy array, your classifier should return a numpy array of length $n$ with classifications. There is a demo in the cell below, and a test you can run before submitting to check your code is working correctly.

Your code must run on our test machine in under 30 seconds. If you wish to train a more complicated model (e.g. neural network) which will take longer, you are welcome to save the model's weights as a file and then load these in the cell below so we can test it. You must include the code which computes the original weights, but this must not run when we run the notebook – comment out the code which actually executes the routine and make sure it is clear what we need to change to get it to run. Remember that we will be testing your final classifier on additional hidden data.

In [3]:
import numpy as np

class Layer:
    def __init__(self, num_of_inputs, num_of_neurons):
        self.weights = 0.01 * np.random.randn(num_of_inputs, num_of_neurons)
        self.biases = np.zeros((1, num_of_neurons))


    def forward_pass(self, inputs):
        self.inputs = inputs
        self.output = np.dot(inputs, self.weights) + self.biases
        return self.output


    def backward_pass(self, output_grad):
        # Gradient on parameters.
        self.weights_grad = np.dot(self.inputs.T, output_grad)
        self.biases_grad = np.sum(output_grad, axis=0, keepdims=True)

        # Gradient on input values to pass to the previous layer.
        self.input_grad = np.dot(output_grad, self.weights.T)

        return self.input_grad


    def update_params(self, learning_rate=1.0):
        # Update parameters using Stochastic Gradient Descent.
        self.weights -= learning_rate * self.weights_grad
        self.biases -= learning_rate * self.biases_grad


class ActivationFunction:
    def __init__(self, is_for_output_layer):
        self.is_for_output_layer = is_for_output_layer


    def forward_pass(self, inputs):
        self.inputs = inputs
        if self.is_for_output_layer:
            self.output = self._calc_sigmoid(inputs)
        else:
            self.output = self._calc_rectifier(inputs)

        return self.output


    def backward_pass(self, output_grad):
        if self.is_for_output_layer:
            self.gradient = output_grad * self._calc_sigmoid_derivative(self.output)
        else:
            self.gradient = output_grad * self._calc_rectifier_derivative(self.inputs)
        return self.gradient
            

    @staticmethod
    def _calc_rectifier(inputs):
        return np.maximum(0, inputs)


    @staticmethod
    def _calc_rectifier_derivative(inputs):
        derivative = np.array(inputs, copy=True)
        derivative[inputs <= 0] = 0
        derivative[inputs > 0] = 1
        return derivative


    @staticmethod
    def _calc_sigmoid(inputs):
        return 1 / (1 + np.exp(-inputs))


    @staticmethod
    def _calc_sigmoid_derivative(output):
        return output * (1 - output)


class MeanSquaredErrorLoss:
    def forward_pass(self, predictions, labels):
        labels = labels.reshape(-1, 1)
        loss = np.mean((predictions - labels) ** 2)
        return loss


    def backward_pass(self, predictions, labels):
        labels = labels.reshape(-1, 1)
        gradient = 2 * (predictions - labels) / len(labels)
        return gradient


class SpamClassifier:
    def train(self, dataset_relative_path, save_to_filename='data/spam_classifier_parameters.npz'):
        self._populate_features_and_labels(dataset_relative_path)
        setup = self._set_up(32)

        batch_size = 50
        num_of_epochs = 1000
        for epoch in range(num_of_epochs + 1):

            total_loss, total_correct = self._go_through_epoch(setup, batch_size)

            if epoch % 100 == 0:
                total_samples = len(self.labels_of_samples)
                num_of_batches = total_samples / batch_size
                mean_epoch_loss = total_loss / num_of_batches
                epoch_accuracy = total_correct / total_samples
                print('='*20 + f' EPOCH {epoch} ' + '='*20+'\n')
                print(f'LOSS: {mean_epoch_loss:.4f}')
                print(f'ACC : {epoch_accuracy:.4f} ({total_correct}/{total_samples})\n')

        print('='*52 + '\n\nTraining completed.')

        layers = setup[0]
        self._save_model(layers, save_to_filename)
        print('Model parameters saved successfully.\n')


    def predict(self, test_data, load_from_filename='data/spam_classifier_parameters.npz'):
        self.samples = test_data
        setup = self._set_up(32)
        layers = setup[0]
        activation_functions = setup[1]

        self._load_model(layers, load_from_filename)

        print('Model parameters loaded successfully.\nTesting...', end=' ')

        # Forward pass.
        neuron_activations = self.samples
        for layer, activation_function in zip(layers, activation_functions):
            neuron_activations = layer.forward_pass(neuron_activations)
            neuron_activations = activation_function.forward_pass(neuron_activations)

        print('Done.\n')

        predicted_labels = (neuron_activations > 0.5).astype(int).flatten()

        return predicted_labels


    def _populate_features_and_labels(self, dataset_relative_path):
        try:
            dataset = np.loadtxt(open(dataset_relative_path), delimiter=',').astype(int)
        except FileNotFoundError:
            print(f'ERROR: "{dataset_relative_path}" file not found.')
            return
        except:
            print(f'ERROR: improper contents or something is wrong with the file/permissions ("{dataset_relative_path}").')
            return

        self.labels_of_samples = dataset[:, 0]
        self.samples = dataset[:, 1:]


    def _set_up(self, num_of_neurons_in_first_hidden_layer):
        num_of_inputs = np.shape(self.samples)[1]

        hidden_layer_1 = Layer(num_of_inputs, num_of_neurons_in_first_hidden_layer)
        activation_function_1 = ActivationFunction(False)

        hidden_layer_2 = Layer(num_of_neurons_in_first_hidden_layer, int(num_of_neurons_in_first_hidden_layer/2))  
        activation_function_2 = ActivationFunction(False)
        
        output_layer = Layer(int(num_of_neurons_in_first_hidden_layer/2), 1)  
        activation_function_output = ActivationFunction(True)

        layers = [ hidden_layer_1, hidden_layer_2, output_layer ]
        activation_functions = [ activation_function_1, activation_function_2, activation_function_output ]

        return layers, activation_functions


    def _go_through_epoch(self, setup, batch_size):
        hidden_layer_1, hidden_layer_2, output_layer = setup[0]
        activation_function_1, activation_function_2, activation_function_output = setup[1]

        total_loss = 0
        total_correct = 0

        for samples_batch, labels_of_samples_batch in self._generate_batches_of_size(batch_size):
            # Forward pass.
            output1 = hidden_layer_1.forward_pass(samples_batch)
            activated_output1 = activation_function_1.forward_pass(output1)

            output2 = hidden_layer_2.forward_pass(activated_output1)
            activated_output2 = activation_function_2.forward_pass(output2)

            final_output = output_layer.forward_pass(activated_output2)
            predictions = activation_function_output.forward_pass(final_output)

            # Calculate loss.
            batch_loss = MeanSquaredErrorLoss().forward_pass(predictions, labels_of_samples_batch)
            total_loss += batch_loss

            # Calculate accuracy.
            predicted_labels = (predictions > 0.5).astype(int)
            correct_predictions = (predicted_labels == labels_of_samples_batch.reshape(-1, 1)).sum()
            total_correct += correct_predictions

            # Backward pass.
            loss_gradient = MeanSquaredErrorLoss().backward_pass(predictions, labels_of_samples_batch)

            grad_output = activation_function_output.backward_pass(loss_gradient)
            grad_layer_out = output_layer.backward_pass(grad_output)

            grad_activation_2 = activation_function_2.backward_pass(grad_layer_out)
            grad_layer_2 = hidden_layer_2.backward_pass(grad_activation_2)

            grad_activation_1 = activation_function_1.backward_pass(grad_layer_2)
            grad_layer_1 = hidden_layer_1.backward_pass(grad_activation_1)

            # Update weights and biases.
            learning_rate = 0.03
            hidden_layer_1.update_params(learning_rate)
            hidden_layer_2.update_params(learning_rate)
            output_layer.update_params(learning_rate)

        return total_loss, total_correct


    def _generate_batches_of_size(self, batch_size):
        num_of_inputs = self.samples.shape[0]
        indices = np.arange(num_of_inputs)
        np.random.shuffle(indices)

        samples_shuffled = self.samples[indices]
        labels_of_samples_shuffled = self.labels_of_samples[indices]

        for i in range(0, num_of_inputs, batch_size):
            samples_batch = samples_shuffled[i:i + batch_size]
            labels_of_samples_batch = labels_of_samples_shuffled[i:i + batch_size]
            yield (samples_batch, labels_of_samples_batch)


    @staticmethod
    def _save_model(layers, filename='model_parameters.npz'):
        data_dict = {}
        for i, layer in enumerate(layers):
            data_dict[f'weights_{i}'] = layer.weights
            data_dict[f'biases_{i}'] = layer.biases

        try:
            np.savez(filename, **data_dict)
        except:
            print(f'ERROR: Something went wrong while saving the file "{filename}".')


    @staticmethod
    def _load_model(layers, filename='model_parameters.npz'):
        try:
            data = np.load(filename)
        except:
            print(f'ERROR: Something went wrong while loading the file "{filename}".')

        for i, layer in enumerate(layers):
            layer.weights = data[f'weights_{i}']
            layer.biases = data[f'biases_{i}']


def create_classifier():
    return SpamClassifier()


classifier = create_classifier()

# train() automatically saves parameters to 'data/spam_classifier_parameters.npz', so please
# make sure to give appropriate permissions to write/read from external files.
#classifier.train('data/training_spam.csv')

# IMPORTANT: When testing the model on hidden data please load the parameters as follows:
# predictions = classifier.predict(test_data, "data/93_percent_parameters.npz")

### Accuracy Estimate
In the cell below there is a function called `my_accuracy_estimate()` which returns `0.5`. Before you submit the assignment, write your best guess for the accuracy of your classifier into this function, as a percentage between `0` and `1`. So if you think you will get 80% of inputs correct, return the value `0.8`. This will form a small part of the marking criteria for the assignment, to encourage you to test your own code.

In [4]:
def my_accuracy_estimate():
    return 0.92

Write all of the code for your classifier above this cell.

### Testing Details
Your classifier will be tested against some hidden data from the same source as the original. The accuracy (percentage of classifications correct) will be calculated, then benchmarked against common methods. At the very high end of the grading scale, your accuracy will also be compared to the best submissions from other students (in your own cohort and others!). Your estimate from the cell above will also factor in, and you will be rewarded for being close to your actual accuracy (overestimates and underestimates will be treated the same).

#### Test Cell
The following code will run your classifier against the provided test data. To enable it, set the constant `SKIP_TESTS` to `False`.

The original skeleton code above classifies every row as ham, but once you have written your own classifier you can run this cell again to test it. So long as your code sets up a variable called `classifier` with a method called `predict`, the test code will be able to run. 

Of course you may wish to test your classifier in additional ways, but you *must* ensure this version still runs before submitting.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [5]:
# IMPORTANT: When testing the model on hidden data please load the parameters as follows:
# predictions = classifier.predict(test_data, "data/93_percent_parameters.npz")

SKIP_TESTS = True

if not SKIP_TESTS:
    testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(int)
    test_data = testing_spam[:, 1:]
    test_labels = testing_spam[:, 0]
    
    # Currently the model loads parameters from the best run that achieved 93% on a 1000/500 split.
    # (I lost the exact values of parameters used in code for this run, however they were not too different from the ones used above)
    # To test predict() after manually training the model above, just delete the second argument.
    predictions = classifier.predict(test_data, "data/93_percent_parameters.npz")
    accuracy = np.count_nonzero(predictions == test_labels)/test_labels.shape[0]
    print(f"Accuracy on test data is: {accuracy}")

In [6]:
import sys
import pathlib

fail = False;

success = '\033[1;32m[✓]\033[0m'
issue = '\033[1;33m[!]'
error = '\033[1;31m\t✗'

#######
##
## Skip Tests check.
##
## Test to ensure the SKIP_TESTS variable is set to True to prevent it slowing down the automarker.
##
#######

if not SKIP_TESTS:
    fail = True;
    print("{} \'SKIP_TESTS\' is incorrectly set to False.\033[0m".format(issue))
    print("{} You must set the SKIP_TESTS constant to True in the cell above.\033[0m".format(error))
else:
    print('{} \'SKIP_TESTS\' is set to true.\033[0m'.format(success))

#######
##
## File Name check.
##
## Test to ensure file has the correct name. This is important for the marking system to correctly process the submission.
##
#######
    
p3 = pathlib.Path('./spamclassifier.ipynb')
if not p3.is_file():
    fail = True
    print("{} The notebook name is incorrect.\033[0m".format(issue))
    print("{} This notebook file must be named spamclassifier.ipynb\033[0m".format(error))
else:
    print('{} The notebook name is correct.\033[0m'.format(success))

#######
##
## Create classifier function check.
##
## Test that checks the create_classifier function exists. The function should train the classifier and return it so that it can be evaluated by the marking system.
##
#######

if "create_classifier" not in dir():
    fail = True;
    print("{} The create_classifier function has not been defined.\033[0m".format(issue))
    print("{} Your code must include a create_classifier function as described in the coursework specification.\033[0m".format(error))
    print("{} If you believe you have, \'restart & run-all\' to clear this error.\033[0m".format(error))
else:
    print('{} The create_classifier function has been defined.\033[0m'.format(success))

#######
##
## Classifier variable check.
##
## Test that checks the classifier variable exists. The marking system will use this variable to make predictions based on a set of random features you have not seen. Your score will be based on how well your classifier predicts the hidden labels.
##
#######

if 'classifier' not in vars():
    fail = True;
    print("{} The classifer variable has not been defined.\033[0m".format(issue))
    print("{} Your code must create a variable called \'classifier\' as described in the coursework specification.\033[0m".format(error))
    print("{} This variable should contain the trained classifier you have created.\033[0m".format(error))
else:
    print('{} The classifer variable has been correctly defined.\033[0m'.format(success))

#######
##
## Accuracy Estimation check.
##
## Test that checks the accuracy estimation function exists and is a reasonable value. This is a requirement of the coursework specification and is used by the marking system when generating your final grade.
##
#######

if "my_accuracy_estimate" not in dir():
    fail = True;
    print("{} The my_accuracy_estimate function has not been defined.\033[0m".format(issue))
    print("{} Your code must include a my_accuracy_estimate function as described in the coursework specification.\033[0m".format(error))
    print("{} If you believe you have, \'restart & run-all\' to clear this error.\033[0m".format(error))
else:
    if my_accuracy_estimate() == 0.5:
        print("{} my_accuracy_estimate function warning.\033[0m".format(issue))
        print("{} my_accuracy_estimate function returns a value of 0.5 - Your classifier is no better than random chance.\033[0m".format(error))
        print("{} Are you sure this is correct.\033[0m".format(error))
    else:
        print('{} The my_accuracy_estimate function has been defined correctly.\033[0m'.format(success))

#######
##
## Test set check.
##
## Test that checks your classifier actually works. The calls made here are the same made by the automarker - albeit with different data. If your work fails this test it will score 0 in the automarker.
##
#######

try:
    testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(int)
    test_data = testing_spam[:, 1:]
    test_labels = testing_spam[:, 0]
    
    try:
        predictions = classifier.predict(test_data)
        accuracy = np.count_nonzero(predictions == test_labels)/test_labels.shape[0]
        print('{0} Success running test set - Accuracy was {1:.2f}%.\033[0m'.format(success, (accuracy*100)))
    except Exception as e:
        fail = True
        print("{} Error running test set.\033[0m".format(issue))
        print("{} Your code produced the following error. This error will result in a zero from the automarker, please fix.\033[0m".format(error))
#         print("{} {}\033[0m".format(error, e))
        print(e)
except:
    sys.stderr.write("Unable to run one test as the file \'data/testing_spam.csv\' could not be found.")

#######
##
## Final Summary
##
## Prints the final results of the submission tests.
##
#######

if fail:
    sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
else:
    print("\033[1m\n\n")
    print("╔═══════════════════════════════════════════════════════════════╗")
    print("║                        Congratulations!                       ║")
    print("║                                                               ║")
    print("║            Your work meets all the required criteria          ║")
    print("║                   and is ready for submission.                ║")
    print("╚═══════════════════════════════════════════════════════════════╝")
    print("\033[0m")
    

[✓] 'SKIP_TESTS' is set to true.
[✓] The notebook name is correct.
[✓] The create_classifier function has been defined.
[✓] The classifer variable has been correctly defined.
[✓] The my_accuracy_estimate function has been defined correctly.
Model parameters loaded successfully.
Testing... Done.

[✓] Success running test set - Accuracy was 92.40%.



╔═══════════════════════════════════════════════════════════════╗
║                        Congratulations!                       ║
║                                                               ║
║            Your work meets all the required criteria          ║
║                   and is ready for submission.                ║
╚═══════════════════════════════════════════════════════════════╝



In [7]:
# This is a test cell. Please do not modify or delete.