# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For the this part of the assignment you will need to submit the implementation for an agent which can solve sudoku puzzles – this notebook:
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

I suggest you implement *constraint satisfaction* as it is described in the unit material. You can use the code you have previously been given as a guide. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%).

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (report), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [1]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [2]:
import numpy as np
import time
import copy

# Frequently used constants, populated in `main()`.
cells = [ (row, column) for row in range(1, 10) for column in range(1, 10) ]
units = { cell: [] for cell in cells }
peers = { }

# Global variable to track the elapsed time since the start of the solution generation.
# IMPORTANT: Ensure `start_time` is defined and used globally to prevent incorrect triggering of 
# the time-out condition in `recursive_depth_first_search`, which could lead to an erroneous 
# `INVALID_SOLUTION` return.
start_time = time.time()

INVALID_SOLUTION = { cell: '-1' for cell in cells }
ALL_AVAILABLE_DIGITS = '123456789'


class ContradictionException(Exception):
    """
    Custom exception used to indicate a contradiction encountered during Sudoku solving.

    This exception is raised when the Sudoku solver reaches a state where a valid solution is no longer possible
    under the current assumptions, necessitating backtracking or termination of the solving process.
    """
    pass


def populate_units():
    """
    Populate the row, column, and 3x3 box units for each cell in a Sudoku grid.

    A 'unit' of a cell is an element of the global `units` dict, where each key is a cell 
    and each value is a list of three lists: all cells on the same row as the key cell, 
    all cells in the same column, and all cells in the same standard 3x3 box of cells.
    """
    # Populate the row and column units.
    for cell in cells:
        row_unit = []
        col_unit = []
        for cell_iter in cells:
            cell_on_the_same_row = cell_iter[0] == cell[0]
            if cell_on_the_same_row:
                row_unit.append(cell_iter)
            cell_in_the_same_column = cell_iter[1] == cell[1]
            if cell_in_the_same_column:
                col_unit.append(cell_iter)
        units[cell] += [row_unit, col_unit]

    # Populate the 3x3 box units.
    for row in range(1, 10, 3):
        for col in range(1, 10, 3):
            box_unit = [ (row+dx, col+dy) for dx in range(3) for dy in range(3) ]
            for cell in box_unit:
                units[cell].append(box_unit)


def populate_peers():
    """
    Populate the peers for each cell in a Sudoku grid.

    A 'peer' of a cell is an element of the global `peers` dict, where each key is a cell
    and each value is a set of all cells that are in the same three units as the key cell.
    Importantly, the key cell itself is excluded from the set.
    """
    for cell in cells:
        # Flatten and exclude the current cell.
        flattened_units_of_a_cell = [ cell_iter for unit in units[cell] for cell_iter in unit if cell_iter != cell ]
        # Convert into a set to enforce uniqueness and allow for O(1) lookups.
        peers[cell] = set(flattened_units_of_a_cell)


def display_sudoku(np_array):
    """
    Display a Sudoku puzzle in a human-readable format.

    Args:
        `np_array` (numpy.ndarray): A 9x9 NumPy array representing the Sudoku puzzle.
    """
    horizontal_separator = '|' + '+'.join(['-------']*3) + '|'
    for i, row in enumerate(np_array):
        if (i % 3 == 0) and (i != 0):
            print(horizontal_separator)
        row_str = '| ' + ' | '.join(' '.join(str(cell) for cell in row[j:j+3]) for j in range(0, 9, 3)) + ' |'
        print(row_str)
    print()


def convert_grid_to_np_array(grid):
    """
    Convert a grid dictionary to a NumPy array representing a Sudoku puzzle.

    Args:
        `grid` (dict): A dictionary where keys are cell coordinates (tuples) and values are strings of available digits.

    Return:
        `np_grid` (numpy.ndarray): A 9x9 NumPy array representing the Sudoku puzzle.
    """
    np_grid = np.empty((9, 9), dtype=object)

    for (row, col), available_digits in grid.items():
        try:
            available_digits = int(available_digits)
        except:
            available_digits = '●'
        np_grid[row-1, col-1] = available_digits

    return np_grid


def find_least_constraining_values(mrv_cell, grid):
    """
    Identify the least constraining values for the given cell using the Least Constraining Value heuristic.

    Args:
        `mrv_cell` (tuple): The cell (row, column) with the Minimum Remaining Values.
        `grid` (dict): The Sudoku grid as a dictionary.

    Return:
        `least_constraining_digits_sorted` (list): A list of digits sorted by their constraining effect on peers.
    """
    count_and_available_digit_pairs = []
    for digit in grid[mrv_cell]:
        occurrence_counter = 0
        for peer in peers[mrv_cell]:
            if digit in grid[peer]:
                occurrence_counter += 1
        count_and_available_digit_pairs.append((occurrence_counter, digit))
    least_constraining_values_sorted_pairs = sorted(count_and_available_digit_pairs, reverse=True)
    least_constraining_digits_sorted = [ pair[1] for pair in least_constraining_values_sorted_pairs ]

    return least_constraining_digits_sorted


def find_cell_with_min_remaining_values(grid):
    """
    Find the cell with the Minimum Remaining Values (remaining available digits) in the Sudoku grid.

    Args:
        `grid` (dict): The Sudoku grid as a dictionary.

    Return:
        `mrv_cell` (tuple or None): The cell with minimum remaining values, or None if no such cell exists.
    """
    mrv_cell = None
    # Any cell has less 9 or less available values, hence choose 10 as "infinity".
    min_remaining_values = 10

    for cell in cells:
        num_of_remaining_values = len(grid[cell])
        if 1 < num_of_remaining_values < min_remaining_values:
            mrv_cell = cell
            if num_of_remaining_values == 2:
                break
            min_remaining_values = num_of_remaining_values

    return mrv_cell


def recursive_depth_first_search(grid):
    """
    Perform a recursive depth-first search to solve the Sudoku puzzle.

    Args:
        `grid` (dict): The Sudoku grid as a dictionary.

    Return:
        `grid` (dict): The solved grid, or INVALID_SOLUTION if no solution exists.
    """
    solution_is_found = all(len(grid[cell]) == 1 for cell in cells)
    elapsed_time = time.time() - start_time
    time_threshold_exceeded = elapsed_time >= 29.99

    # Base case that may terminate recursion early.
    if solution_is_found:
        return grid
    elif time_threshold_exceeded:
        return INVALID_SOLUTION

    # Define the Minimum Remaining Values and Least Constraining Values heuristics.
    mrv_cell = find_cell_with_min_remaining_values(grid)
    # This should never happen, however it is better to be safe than sorry.
    if mrv_cell is None:
        return INVALID_SOLUTION
    least_constraining_digits_sorted = find_least_constraining_values(mrv_cell, grid)

    for digit in least_constraining_digits_sorted:
        new_grid = grid.copy()
        try:
            new_grid = constrain_cell_to_single_digit(digit, mrv_cell, new_grid)
            solution = recursive_depth_first_search(new_grid)
            solution_is_valid = not np.array_equal(solution, INVALID_SOLUTION)
            if solution_is_valid:
                return solution
        except ContradictionException:
            # If a contradiction is encountered, discard this branch and try the next digit.
            pass

    # If all possibilities are exhausted without finding a valid solution, return an invalid solution.
    return INVALID_SOLUTION


def fill_in_hidden_singles(digit, cell, grid):
    """
    Fill in hidden singles for the given digit and cell in the Sudoku grid.

    Args:
        `digit` (str): The digit to check for hidden singles.
        `cell` (tuple): The cell (row, column) in the grid.
        `grid` (dict): The Sudoku grid as a dictionary.

    Return:
        `grid` (dict): The updated grid after filling in hidden singles.
    """
    for unit in units[cell]:
        num_of_occurences_in_unit = 0
        last_occured_in_cell = None

        for cell_in_unit in unit:
            if digit in grid[cell_in_unit]:
                num_of_occurences_in_unit += 1
                last_occured_in_cell = cell_in_unit

        if (last_occured_in_cell) and (num_of_occurences_in_unit == 1):
            grid = constrain_cell_to_single_digit(digit, last_occured_in_cell, grid)
        elif not last_occured_in_cell:
            raise ContradictionException

    return grid


def eliminate_current_digit_from_peers(cell, grid):
    """
    Eliminate the current digit from the peers of the given cell.

    Args:
        `cell` (tuple): The cell (row, column) from which to eliminate the digit.
        `grid` (dict): The Sudoku grid as a dictionary.

    Return:
        `grid` (dict): The updated grid after elimination.
    """
    for peer in peers[cell]:
        grid = propagate_digit_elimination(grid[cell], peer, grid)

    return grid


def check_for_naked_twins(cell, grid):
    """
    Check for and process naked twins in the units of the specified cell.

    Args:
        `cell` (tuple): The cell (row, column) to check for naked twins.
        `grid` (dict): The Sudoku grid as a dictionary.

    Return:
        `grid` (dict): The updated grid after processing naked twins.
    """
    for unit in units[cell]:
        for potential_naked_twin in unit:

            naked_twins_found = (len(grid[potential_naked_twin]) == 2) and (grid[cell] in grid[potential_naked_twin]) and (potential_naked_twin != cell)

            if naked_twins_found:
                naked_twin = potential_naked_twin
                first_twin_digit = grid[naked_twin][0]
                second_twin_digit = grid[naked_twin][1]

                for cell_of_unit in unit:
                    if (cell_of_unit != naked_twin) and (cell_of_unit != cell):
                        grid = propagate_digit_elimination(first_twin_digit, cell_of_unit, grid)
                        grid = propagate_digit_elimination(second_twin_digit, cell_of_unit, grid)

        if naked_twins_found:
            break

    return grid


def propagate_digit_elimination(digit, cell, grid):
    """
    Propagate the elimination of a digit (i.e. recursively) from a specified cell throughout the grid.

    Args:
        `digit` (str): The digit to eliminate.
        `cell` (tuple): The cell (row, column) from which to eliminate the digit.
        `grid` (dict): The Sudoku grid as a dictionary.

    Return:
        `grid` (dict): The updated grid after propagating digit elimination.
    """
    digit_is_present = digit in grid[cell]

    if digit_is_present:
        grid[cell] = grid[cell].replace(digit, '')
    else:
        return grid

    num_of_remaining_digits = len(grid[cell])

    if num_of_remaining_digits == 2:
        grid = check_for_naked_twins(cell, grid)
    elif num_of_remaining_digits == 1:
        grid = eliminate_current_digit_from_peers(cell, grid)
    elif num_of_remaining_digits == 0:
        raise ContradictionException

    grid = fill_in_hidden_singles(digit, cell, grid)

    return grid


def constrain_cell_to_single_digit(digit, cell, grid):
    """
    Constrain a cell to a single digit and propagate this constraint through the grid.

    Args:
        `digit` (str): The digit to assign to the cell.
        `cell` (tuple): The cell (row, column) to constrain.
        `grid` (dict): The Sudoku grid as a dictionary.

    Return:
        `grid` (dict): The updated grid after constraining the cell.
    """
    for digit_to_be_eliminated in grid[cell]:
        if digit_to_be_eliminated != digit:
            grid = propagate_digit_elimination(digit_to_be_eliminated, cell, grid)

    return grid


def initialize_grid_with_given_digits(given_digits):
    """
    Initialize the Sudoku grid with the given digits.

    The `grid` is a dictionary with 81 keys as all possible cells, and strings 
    of digits that can be assigned to a cell as their corresponding values.

    Args:
        `given_digits` (list): A list of digits to initialize the grid with.

    Return:
        `grid` (dict): The initialized grid, or INVALID_SOLUTION if a contradiction occurs.
    """
    grid = { cell: ALL_AVAILABLE_DIGITS for cell in cells }

    for digit, cell in zip(given_digits, cells):
        cell_is_empty = digit == '0'

        if cell_is_empty:
            continue

        try:
            grid = constrain_cell_to_single_digit(digit, cell, grid)
        except ContradictionException:
            return INVALID_SOLUTION

    return grid
                

def sudoku_solver(numpy_array):
    """
    Generate a solution to a Sudoku puzzle represented as a NumPy array.

    Args:
        `numpy_array` (numpy.ndarray): A 9x9 NumPy array representing a Sudoku puzzle, where 0 denotes an empty cell.

    Return:
        `numpy_array_solution` (numpy.ndarray): A 9x9 NumPy array representing the solved Sudoku puzzle, or an array filled with -1 if no solution is found.
    """
    flattened_numpy_array = [ str(item_cell) for array in numpy_array for item_cell in array ]
    grid = initialize_grid_with_given_digits(flattened_numpy_array)
    grid_solution = recursive_depth_first_search(grid)
    numpy_array_solution = convert_grid_to_np_array(grid_solution)

    return numpy_array_solution


def main():
    global start_time

    populate_units()
    populate_peers()

    difficulty = 'hard'
    sudokus = np.load(f'data/{difficulty}_puzzle.npy')
    sudokus_solutions = np.load(f'data/{difficulty}_solution.npy').astype(int)

    print('Generating solutions...')

    solving_times = []
    incorrect_solutions_counter = 0
    num_of_sudokus = len(sudokus)

    sudoku_output_enabled = True
    if sudoku_output_enabled:
        test_n_times = 1
    else:
        test_n_times = 128

    print(f'The test (difficulty "{difficulty}") will be run {test_n_times} time(s).', end='\n\n')

    for n in range(test_n_times):
        for i in range(num_of_sudokus):
            sudoku = copy.deepcopy(sudokus[i])
            if sudoku_output_enabled:
                print(f'Sudoku number {i+1}:')
                display_sudoku(sudoku)

            # IMPORTANT: It is mandatory to use `time.time()` when testing, failure to do
            # so may result in erroneous assignment of `INVALID_SOLUTION` to `solution`.
            start_time = time.time()

            solution = sudoku_solver(sudoku)

            end_time = time.time()
            solving_time = end_time - start_time
            solving_times.append(solving_time)

            if sudoku_output_enabled:
                print(f'Generated solution (generated in {round(solving_time, 4)} seconds):')
                display_sudoku(solution)
                print('Actual solution:')
                display_sudoku(sudokus_solutions[i])

            if not np.array_equal(solution, sudokus_solutions[i]):
                print('ERROR: The generated solution does not match the actual one.')
                incorrect_solutions_counter += 1

            if sudoku_output_enabled:
                print('='*64, end='\n\n')

        num_of_correct_solutions = num_of_sudokus - incorrect_solutions_counter
        print(f'Test {n+1}/{test_n_times} completed.')
        print(f'{num_of_correct_solutions}/{num_of_sudokus} solutions are correct.', end='\n\n')

    average_time = round(sum(solving_times) / len(solving_times), 4)
    max_time = round(max(solving_times), 4)
    print(f'Average solving time: {average_time} seconds')
    print(f'Maximum solving time: {max_time} seconds')


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print('\nKEYBOARD INTERRUPT INITIATED.')
    except Exception as e:
        print(f'ERROR:\n{e}')


Generating solutions...
The test (difficulty "hard") will be run 1 time(s).

Sudoku number 1:
| 0 0 0 | 0 0 7 | 5 4 0 |
| 9 0 6 | 0 5 0 | 0 3 0 |
| 0 0 0 | 0 0 0 | 2 0 0 |
|-------+-------+-------|
| 2 0 0 | 0 0 0 | 7 9 0 |
| 0 0 3 | 0 4 1 | 0 0 0 |
| 7 0 0 | 0 0 0 | 0 5 0 |
|-------+-------+-------|
| 0 3 0 | 0 0 4 | 0 2 0 |
| 0 9 4 | 1 0 0 | 0 0 0 |
| 0 0 0 | 5 9 0 | 0 0 4 |

Generated solution (generated in 0.0015 seconds):
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
|-------+-------+-------|
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
|-------+-------+-------|
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |

Actual solution:
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
|-------+-------+-------|
| -1 -1 -1 | -1 -1 -1 | -1 -1 -1 |
| -1 -1 -1 | -1 -1

All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 30 seconds each on the test machine to count as successful, but you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [3]:
SKIP_TESTS = True
start_time = time.time()

if not SKIP_TESTS:
    import time
    import numpy as np
    __SCORES = {}
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i+1)
            print(sudoku)
            
            start_time = time.time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.time()
            
            if not isinstance(your_solution, np.ndarray):
                print("\033[91m[ERROR] Your sudoku_solver function returned a variable that has the incorrect type. If you submit this it will likely fail the auto-marking procedure result in a mark of 0 as it is expecting the function to return a numpy array with a shape (9,9).\n\t\033[94mYour function returns a {} object when {} was expected.\n\x1b[m".format(type(your_solution), np.ndarray))
            elif not np.all(your_solution.shape == (9, 9)):
                print("\033[91m[ERROR] Your sudoku_solver function returned an array that has the incorrect shape.  If you submit this it will likely fail the auto-marking procedure result in a mark of 0 as it is expecting the function to return a numpy array with a shape (9,9).\n\t\033[94mYour function returns an array with shape {} when {} was expected.\n\x1b[m".format(your_solution.shape, (9, 9)))
            
            print(f"This is your solution for {difficulty} sudoku number", i+1)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took {} seconds to solve.\n".format(end_time-start_time))

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        __SCORES[difficulty] = {
            'correct': count,
            'total': len(sudokus)
        }

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [4]:
import sys
import pathlib

fail = False;

success = '\033[1;32m[✓]\033[0m'
issue = '\033[1;33m[!]'
error = '\033[1;31m\t✗'
indent_success = '\033[1;32m\t✓'

#######
##
## Skip Tests check.
##
## Test to ensure the SKIP_TESTS variable is set to True to prevent it slowing down the automarker.
##
#######

if not SKIP_TESTS:
    fail = True;
    print("{} \'SKIP_TESTS\' is incorrectly set to False.\033[0m".format(issue))
    print("{} You must set the SKIP_TESTS constant to True in the cell above.\033[0m".format(error))
else:
    print('{} \'SKIP_TESTS\' is set to true.\033[0m'.format(success))

#######
##
## Report File Check.
##
## Test that checks there is a report pdf file found in the same folder as the notebook. This is required by the coursework specification.
##
#######

p1 = pathlib.Path('./report.pdf')
p2 = pathlib.Path('./Report.pdf')
if not (p1.is_file() or p2.is_file()):
    fail = True;
    print("{} Report PDF not found.\033[0m".format(issue))
    print("{} You must include a separate file called report.pdf in your submission.\033[0m".format(error))
else:
    print('{} Report PDF found.\033[0m'.format(success))

#######
##
## File Name check.
##
## Test to ensure file has the correct name. This is important for the marking system to correctly process the submission.
##
#######
    
p3 = pathlib.Path('./sudoku.ipynb')
if not p3.is_file():
    fail = True
    print("{} The notebook name is incorrect.\033[0m".format(issue))
    print("{} This notebook file must be named sudoku.ipynb\033[0m".format(error))
else:
    print('{} The notebook name is correct.\033[0m'.format(success))

#######
##
## Create classifier function check.
##
## Test that checks the create_classifier function exists. The function should train the classifier and return it so that it can be evaluated by the marking system.
##
#######

if "sudoku_solver" not in dir():
    fail = True;
    print("{} The sudoku_solver function has not been defined.\033[0m".format(issue))
    print("{} Your code must include a sudoku_solver function as described in the coursework specification.\033[0m".format(error))
    print("{} If you believe you have, \'restart & run-all\' to clear this error.\033[0m".format(error))
else:
    print('{} The sudoku_solver function has been defined.\033[0m'.format(success))



try:
    _sudoku = np.load("data/very_easy_puzzle.npy")[0]
    _solution = np.load("data/very_easy_solution.npy")[0]

    if not np.array_equal(sudoku_solver(_sudoku), _solution):
        print("{} Your sudoku_solver function does not correctly solve the first sudoku.\033[0m".format(issue))
        print()
        print("{} Your assignment is unlikely to get any marks from the autograder. While we will\033[0m".format(error))
        print("{} try to check it manually to assign some partial credit, we encourage you to ask\033[0m".format(error))
        print("{} for help on the forum or directly to a tutor.\033[0m".format(error))
        print()
        print("{} Please use the report file to explain your code anyway.\033[0m".format(error))
    else:
        print("{} Your sudoku_solver function correctly solves the first sudoku.\033[0m".format(success))
        if "__SCORES" in dir():
#             print("{} Test set summary - Not Found.\033[0m".format(issue))
#             print("{} Test set summary could not be found. This is automatically generated when the \033[0m".format(error))
#             print("{} above test cell is run. If you would like to see the summary please run the above cell.\033[0m".format(error))
#             print("{} You do not need this for submission, it is only for your convenience.\033[0m".format(error))
#         else:
            correct = 0
            total = 0
            for key, value in __SCORES.items():
                correct += value['correct']
                total += value['total']
                
            print("{} Test set summary - {}/{} Correct.\033[0m".format(issue, correct, total))
            if total != correct:
                
                for key, value in __SCORES.items():
                    if value['correct'] == value['total']:
                        print("{} {}/{} of {} sudokus correct.\033[0m".format(indent_success, value['correct'], value['total'], key))
                    else:
                        print("{} {}/{} of {} sudokus correct.\033[0m".format(error, value['correct'], value['total'], key))
            
except Exception as e:
    fail = True
    print("{} Error running test set.\033[0m".format(issue))
    print("{} Your code produced the following error. This error will result in a zero from the automarker, please fix.\033[0m".format(error))
    print(e)

    

#######
##
## Final Summary
##
## Prints the final results of the submission tests.
##
#######

if fail:
    sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
else:
    print("\033[1m\n\n")
    print("╔═══════════════════════════════════════════════════════════════╗")
    print("║                        Congratulations!                       ║")
    print("║                                                               ║")
    print("║            Your work meets all the required criteria          ║")
    print("║                   and is ready for submission.                ║")
    print("╚═══════════════════════════════════════════════════════════════╝")
    print("\033[0m")
    

[✓] 'SKIP_TESTS' is set to true.
[✓] Report PDF found.
[✓] The notebook name is correct.
[✓] The sudoku_solver function has been defined.
[✓] Your sudoku_solver function correctly solves the first sudoku.



╔═══════════════════════════════════════════════════════════════╗
║                        Congratulations!                       ║
║                                                               ║
║            Your work meets all the required criteria          ║
║                   and is ready for submission.                ║
╚═══════════════════════════════════════════════════════════════╝



In [5]:
# This is a TEST CELL. Do not delete or change.